spring:
  data: 
    mongodb:
      host: 172.20.100.7
      port: 27017
      database: billing_reports
      
  application:
    name: USERS-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://172.20.100.7:8761/eureka/


server:
  port: 9898
